services:
  - type: web
    name: blankdeploy
    runtime: static
    branch: main
    buildCommand: npm install -g pnpm && pnpm install --frozen-lockfile && pnpm --filter @workspace/web run build
    staticPublishPath: ./artifacts/web/dist/public
    envVars:
      - key: NODE_ENV
        value: production
      - key: BASE_PATH
        value: /
      - key: PORT
        value: 3000
