services:
  - type: web
    name: I am Blank Page
    runtime: static
    branch: main
    buildCommand: npm install -g pnpm && pnpm install && pnpm --filter @workspace/I am blank Page WorkSP run build
    staticPublishPath: ./artifacts/I am blank Page WorkSP/dist/public
    envVars:
      - key: NODE_ENV
        value: production
      - key: BASE_PATH
        value: /
      - key: PORT
        value: 3000
